name: universal_sambat_sdk
description: A Flutter package for Universal Sambat SDK with a pure Dart BS/AD engine, date widgets, converter widgets, themes, and bilingual support.
version: 1.0.0
homepage: https://github.com/kushalkhadkaa/universal-sambat-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
