'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');

const requiredFiles = [
  'LICENSE',
  'package.json',
  'package-lock.json',
  'dist/nepali-datepicker.js',
  'dist/nepali-datepicker.esm.js',
  'dist/nepali-datepicker.cjs.js',
  'dist/nepali-datepicker.css',
  'dist/nepali-datepicker.d.ts',
  'src/js/ndp-data.js',
  'src/js/ndp-utils.js',
  'src/js/ndp-core.js',
  'src/js/ndp-converter-widget.js',
  'robots.txt',
  'sitemap.xml'
];

function walk(dir, matches) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = path.relative(ROOT, fullPath);

    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '.git') continue;
      walk(fullPath, matches);
      continue;
    }

    if (entry.name === '.DS_Store') matches.push(relPath);
  }
}

const forbiddenText = [
  {
    pattern: /['"]-sambat-sdk\//,
    message: 'Broken package scope; use @universal-sambat-sdk/...'
  },
  {
    pattern: /dist\/style\.css/,
    message: 'Framework templates should import universal-sambat-sdk/css, not a non-existent dist/style.css.'
  },
  {
    pattern: /nepali-datepicker\.min\.(js|css)/,
    message: 'Minified dist filenames are not generated by the current build.'
  },
  {
    pattern: /nepali-datepicker-pro\.zip/,
    message: 'Old ZIP download is ignored and not part of the public release.'
  },
  {
    pattern: /nepali-datepicker-studio/,
    message: 'Old package slug remains; use universal-sambat-sdk.'
  },
  {
    pattern: /Nepali DatePicker Studio/,
    message: 'Old product name remains; use Universal Sambat SDK.'
  }
];

function walkFiles(dir, files) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = path.relative(ROOT, fullPath);

    if (entry.isDirectory()) {
      if (entry.name === 'node_modules' || entry.name === '.git') continue;
      walkFiles(fullPath, files);
      continue;
    }

    files.push({ fullPath, relPath });
  }
}

const errors = [];

for (const file of requiredFiles) {
  if (!fs.existsSync(path.join(ROOT, file))) {
    errors.push(`Missing required release file: ${file}`);
  }
}

const dsStoreFiles = [];
walk(ROOT, dsStoreFiles);
for (const file of dsStoreFiles) {
  errors.push(`Remove macOS metadata file: ${file}`);
}

const files = [];
walkFiles(ROOT, files);
for (const { fullPath, relPath } of files) {
  if (relPath === 'scripts/lint.js') continue;

  const ext = path.extname(relPath).toLowerCase();
  const isTextFile = [
    '.js', '.jsx', '.ts', '.tsx', '.json', '.html', '.css', '.md',
    '.txt', '.xml', '.yaml', '.yml', '.php', '.py', '.dart', '.swift',
    '.kt', '.kts', '.svelte', '.vue'
  ].includes(ext) || relPath === 'package-lock.json';

  if (!isTextFile) continue;

  const content = fs.readFileSync(fullPath, 'utf8');
  for (const rule of forbiddenText) {
    if (rule.pattern.test(content)) {
      errors.push(`${relPath}: ${rule.message}`);
    }
  }
}

if (errors.length) {
  console.error('Repository lint failed:\n');
  for (const error of errors) console.error(`- ${error}`);
  process.exit(1);
}

console.log('Repository lint passed.');
